/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.*;
//import java.io.*;

public class App {

    public static void main(String[] args) throws ParseException {

        //***Definition Stage***
        // create Options object
        Options options = new Options();

        // add option "-h" and "--help"
        Option help = new Option("h", "help" ,false, "print usage message");
        options.addOption(help);

        // add option "-b" and "--batch"
        Option batch = Option.builder("b")
                .argName("file")
                .hasArg(true)
                .longOpt("batch")
                .desc("batch file containing expressions to evaluate")
                .build();
        options.addOption(batch);

        //add option "-o" and "--output"
        Option output = Option.builder("o")
                .argName("file").hasArg(true)
                .longOpt("output")
                .desc("output file")
                .build();
        options.addOption(output);

        HelpFormatter formatter = new HelpFormatter();
        String header = "Evaluation of simple mathematical expressions\n";
        String footer = "\nCopyright (C) 2022 Baylor McElroy";

        //***Parsing Stage***
        //Create a parser
        CommandLineParser parser = new DefaultParser();

        //parse the options passed as command line arguments
        CommandLine cmd = parser.parse(options, args);

        //***Interrogation Stage***
        //hasOptions checks if option is present or not
        if (cmd.hasOption("h")) {
            formatter.printHelp("Evaluator",header, options, footer, true);
        }
        if(cmd.hasOption("o")) {
            System.out.println(outCmd(cmd));
        } else if(cmd.hasOption("b")) {
            System.out.println(batchCmd(cmd));
        }
    }
    public static String batchCmd(CommandLine cmd) {
        String str;
        String fileName = cmd.getOptionValue("b");

        str = "Batch value: " + fileName;
        return str;
    }
    public static String outCmd(CommandLine cmd) {
        String str;
        String fileName = cmd.getOptionValue("o");
        str = "Output value: " + fileName;
        return str;
    }
}
