/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.*;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args) throws ParseException, IOException {

        //***Definition Stage***
        // create Options object
        Options options = new Options();

        // add option "-h" and "--help"
        Option help = new Option("h", "help" ,false, "print usage message");
        options.addOption(help);

        // add option "-b" and "--batch"
        Option batch = Option.builder("b")
                .argName("file")
                .hasArg(true)
                .longOpt("batch")
                .desc("batch file containing expressions to evaluate, must be in user directory")
                .build();
        options.addOption(batch);

        //add option "-o" and "--output"
        Option output = Option.builder("o")
                .argName("file").hasArg(true)
                .longOpt("output")
                .desc("output file")
                .build();
        options.addOption(output);

        HelpFormatter formatter = new HelpFormatter();
        String header = "Evaluation of simple mathematical expressions\n";
        String footer = "\nCopyright (C) 2022 Baylor McElroy";

        //***Parsing Stage***
        //Create a parser
        CommandLineParser parser = new DefaultParser();

        //parse the options passed as command line arguments
        CommandLine cmd = parser.parse(options, args);

        //***Interrogation Stage***

        if(args[0].equals("eval")) {
//
            if(cmd.hasOption("b")) {
                String fileName = cmd.getOptionValue("b");
                String userDirectory = System.getProperty("user.dir");
                Path path = Paths.get(userDirectory);
                System.out.println(fileName);
                System.out.println(path.getParent().toString());

                fileName = path.getParent().toString() + "\\" + fileName;
                Evaluator.runEvaluatorBat(fileName);
            }
            else {
                Evaluator.runEvaluatorCmd();
            }
        }
        //hasOptions checks if option is present or not
        else if (cmd.hasOption("h")) {
            formatter.printHelp("Evaluator",header, options, footer, true);
        }

    }
}
